Improve log messaging wording & context

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -112,77 +112,82 @@ runs:
     - name: Build
       shell: bash
       run: |
+        STEPS="[\033[95m STEPS \033[0m]"
+        INFO="[\033[94m INFO \033[0m]"
+        SUCCESS="[\033[92m SUCCESS \033[0m]"
+        WARNING="[\033[93m WARNING \033[0m]"
+        ERROR="[\033[91m ERROR \033[0m]"
+
         cd ${{ github.action_path }}
-        echo -e "Current running path: [ ${PWD} ]"
+        echo -e "${INFO} Current running path: [ ${PWD} ]"
         build_target="${{ inputs.build_target }}"
         [[ -z "${build_target}" ]] && build_target="armbian"
 
         if [[ "${build_target}" == "armbian" ]]; then
 
             cd ${{ github.action_path }}
-            echo -e "Start rebuilding Armbian..."
+            echo -e "${STEPS} Setting up build..."
 
             armbian_file="${{ inputs.armbian_path }}"
             armbian_filename="${armbian_file##*/}"
             armbian_filepath="build/output/images"
-            echo -e "Get armbian file input parameters: [ ${armbian_file} ]"
-            [[ -z "${armbian_file}" ]] && echo -e "The [ armbian_path ] variable must be specified." && exit 1
+            [[ -z "${armbian_file}" ]] && echo -e "${ERROR} The [ armbian_path ] variable must be specified." && exit 1
             [[ -d "${armbian_filepath}" ]] || mkdir -p ${armbian_filepath}
             if [[ "${armbian_file}" == http* ]]; then
-                echo -e "Download file: [ ${armbian_file} ]"
+                echo -e "${STEPS} Downloading Armbian file: [ ${armbian_file} ]"
                 curl -fsSL "${armbian_file}" -o "${armbian_filepath}/${armbian_filename}"
             else
                 if [[ -z "$(ls ${armbian_filepath}/${armbian_filename} 2>/dev/null)" ]]; then
-                    echo -e "Copy files: [ ${armbian_file} ]"
                     cp -vf ${GITHUB_WORKSPACE}/${armbian_file} ${armbian_filepath} 2>/dev/null
                 else
-                    echo -e "The [ ${armbian_filepath}/${armbian_filename} ] file already exists, skipping."
+                    echo -e "${WARNING} The [ ${armbian_filepath}/${armbian_filename} ] file already exists, not overwriting."
                 fi
             fi
             sync
-            echo -e "About the [ ${armbian_filepath} ] directory: \n$(ls -lh ${armbian_filepath} 2>/dev/null)"
+            echo -e "${INFO} Files in [ ${armbian_filepath} ]: \n$(ls -lh ${armbian_filepath} 2>/dev/null)"
 
             cd ${armbian_filepath}
-            echo -e "Check the Armbian file format..."
+            echo -e "${STEPS} Verifying the Armbian file's format..."
             down_file="$(ls -l *.img* 2>/dev/null | grep "^-" | awk '{print $9}' | sort -u | head -n 1)"
-            if [[ -n "${down_file}" ]]; then
-                echo -e "Selected Armbian file: [ ${down_file} ]"
-            else
-                echo -e "The Armbian file is invalid."
+            if [[ -z "${down_file}" ]]; then
+                echo -e "${ERROR} The Armbian file is invalid."
                 exit 1
             fi
             [[ "${down_file:0-7}" == ".img.gz" ]] && gzip -df ${down_file} 2>/dev/null && sync
             [[ "${down_file:0-7}" == ".img.xz" ]] && xz -d ${down_file} 2>/dev/null && sync
             [[ "${down_file:0-4}" == ".zip" ]] && unzip -o ${down_file} 2>/dev/null && sync
-            echo -e "Armbian file: \n$(ls -lh *.img 2>/dev/null)"
+            echo -e "${INFO} Using Armbian file: \n$(ls -lh *.img 2>/dev/null)"
 
-            echo -e "Check the armbian file name (-trunk_)..."
+            echo -e "${STEPS} Verifying the Armbian file name (-trunk_)..."
             image_file="$(ls *.img 2>/dev/null | head -n 1)"
             if [[ "${image_file}" =~ "-trunk_" ]]; then
-                echo -e "The armbian file name is correct."
+                echo -e "${SUCCESS} The Armbian file name is correct."
             else
-                echo -e "Modify Armbian filename..."
+                echo -e "${STEPS} Armbian file name was incorrect, modifying..."
                 image_version="$(echo ${image_file} | grep -oE '[2-9][0-9]\.[0-9]{1,2}\.[0-9]{1,2}' | head -n 1)"
                 image_kernel="$(echo ${image_file} | grep -oE '[5-9]\.[0-9]{1,2}\.[0-9]{1,3}' | head -n 1)"
                 image_save_name="Armbian_${image_version}-trunk_${image_kernel}.img"
                 rm -f ${image_save_name}
                 mv -f ${image_file} ${image_save_name}
-                echo -e "Renamed Armbian file: [ ${image_save_name} ]"
+                echo -e "${INFO} Renamed Armbian file to [ ${image_save_name} ]"
             fi
 
             cd ${{ github.action_path }}
-            echo -e "Start to rebuild armbian..."
-            make_command=""
-            [[ -n "${{ inputs.armbian_board }}" ]] && make_command="${make_command} -b ${{ inputs.armbian_board }}"
-            [[ -n "${{ inputs.kernel_repo }}" ]] && make_command="${make_command} -r ${{ inputs.kernel_repo }}"
-            [[ -n "${{ inputs.kernel_usage }}" ]] && make_command="${make_command} -u ${{ inputs.kernel_usage }}"
-            [[ -n "${{ inputs.armbian_kernel }}" ]] && make_command="${make_command} -k ${{ inputs.armbian_kernel }}"
-            [[ -n "${{ inputs.auto_kernel }}" ]] && make_command="${make_command} -a ${{ inputs.auto_kernel }}"
-            [[ -n "${{ inputs.armbian_fstype }}" ]] && make_command="${make_command} -t ${{ inputs.armbian_fstype }}"
-            [[ -n "${{ inputs.armbian_size }}" ]] && make_command="${make_command} -s ${{ inputs.armbian_size }}"
-            [[ -n "${{ inputs.builder_name }}" ]] && make_command="${make_command} -n ${{ inputs.builder_name }}"
-            sudo ./rebuild ${make_command}
+            echo -e "${STEPS} Rebuilding Armbian..."
+            rebuild_command=""
+            [[ -n "${{ inputs.armbian_board }}" ]] && rebuild_command="${rebuild_command} -b ${{ inputs.armbian_board }}"
+            [[ -n "${{ inputs.kernel_repo }}" ]] && rebuild_command="${rebuild_command} -r ${{ inputs.kernel_repo }}"
+            [[ -n "${{ inputs.kernel_usage }}" ]] && rebuild_command="${rebuild_command} -u ${{ inputs.kernel_usage }}"
+            [[ -n "${{ inputs.armbian_kernel }}" ]] && rebuild_command="${rebuild_command} -k ${{ inputs.armbian_kernel }}"
+            [[ -n "${{ inputs.auto_kernel }}" ]] && rebuild_command="${rebuild_command} -a ${{ inputs.auto_kernel }}"
+            [[ -n "${{ inputs.armbian_fstype }}" ]] && rebuild_command="${rebuild_command} -t ${{ inputs.armbian_fstype }}"
+            [[ -n "${{ inputs.armbian_size }}" ]] && rebuild_command="${rebuild_command} -s ${{ inputs.armbian_size }}"
+            [[ -n "${{ inputs.builder_name }}" ]] && rebuild_command="${rebuild_command} -n ${{ inputs.builder_name }}"
+            echo -e "${INFO} Full rebuild command: ./rebuild ${rebuild_command}"
+            sudo ./rebuild ${rebuild_command}
+            echo -e "${SUCCESS} Rebuilt Armbian."
 
+            echo -e "${STEPS} Compressing Armbian image file..."
             cd ${{ github.action_path }}/${armbian_filepath}
             # Compress Armbian image file
             pigz -qf *.img || gzip -qf *.img
@@ -192,79 +197,88 @@ runs:
             sync && sleep 3
 
             cd ${{ github.action_path }}
-            echo -e "Output variables."
             echo "output_path=${PWD}/${armbian_filepath}" >> ${GITHUB_OUTPUT}
             echo "build_date=$(date +"%m.%d.%H%M")" >> ${GITHUB_OUTPUT}
             echo "status=success" >> ${GITHUB_OUTPUT}
-            echo -e "output_path: ${PWD}/${armbian_filepath}"
-            echo -e "build_date: $(date +"%m.%d.%H%M")"
-            echo -e "status: success"
-            echo -e "output_path files list: \n$(ls -lh ${PWD}/${armbian_filepath}/ 2>/dev/null)"
+            
+            echo -e "${INFO} Final workflow output variables:"
+            echo -e "    output_path: ${PWD}/${armbian_filepath}"
+            echo -e "    build_date: $(date +"%m.%d.%H%M")"
+            echo -e "    status: success"
+            echo -e "    output_path files list: \n$(ls -lh ${PWD}/${armbian_filepath}/ 2>/dev/null)"
 
         elif [[ "${build_target}" == "kernel" ]]; then
 
             cd ${{ github.action_path }}
-            echo -e "Start compile kernel..."
+            echo -e "${STEPS} Compiling kernel..."
 
             config_filepath="compile-kernel/tools/config"
             kernel_outpath="compile-kernel/output"
             [[ -d "${config_filepath}" ]] || mkdir -p ${config_filepath}
             if [[ -n "${{ inputs.kernel_config }}" && "${{ inputs.kernel_config }}" != "false" ]]; then
                 if [[ "$(ls ${GITHUB_WORKSPACE}/${{ inputs.kernel_config }}/config-* -l 2>/dev/null | grep "^-" | wc -l)" -ne "0" ]]; then
-                    echo -e "Use a custom kernel compilation template..."
+                    echo -e "${INFO} Using custom kernel configs from [ ${{ inputs.kernel_config }} ]..."
                     rm -f ${config_filepath}/* 2>/dev/null && sync
                     cp -vf ${GITHUB_WORKSPACE}/${{ inputs.kernel_config }}/config-* ${config_filepath}/ 2>/dev/null && sync
-                    echo -e "List of Kernel Custom Compilation Configuration Templates: \n$(ls -lh ${config_filepath})"
+                    echo -e "${INFO} Custom kernel configs: \n$(ls -lh ${config_filepath})"
                 else
-                    echo -e "The custom kernel compilation template path is invalid, continue to use the default template."
+                    echo -e "${ERROR} The custom kernel config path is invalid: [ ${{ inputs.kernel_config }} ]"
+                    exit 1
                 fi
             else
-                echo -e "Use the default kernel compilation template."
+                echo -e "${INFO} Using the default kernel configs."
             fi
-
+            
+      
             custom_kernel_patch="compile-kernel/tools/patch"
             [[ -d "${custom_kernel_patch}" ]] || mkdir -p ${custom_kernel_patch}
             if [[ -n "${{ inputs.kernel_patch }}" && "${{ inputs.kernel_patch }}" != "false" ]]; then
                 if [[ -d "${GITHUB_WORKSPACE}/${{ inputs.kernel_patch }}" ]]; then
-                    echo -e "Use custom kernel patches..."
+                    echo -e "${INFO} Using custom kernel patches from [ ${{ inputs.kernel_patch }} ]..."
                     rm -rf ${custom_kernel_patch}/* 2>/dev/null && sync
                     cp -vrf ${GITHUB_WORKSPACE}/${{ inputs.kernel_patch }}/* -t ${custom_kernel_patch} && sync
                     echo -e "Directory of custom kernel patches: \n$(ls -lh ${custom_kernel_patch})"
                 else
-                    echo -e "Invalid custom kernel patch directory, skipping."
+                    echo -e "${ERROR} Invalid kernel patch directory: [ ${{ inputs.kernel_patch }} ]"
+                    exit 1
                 fi
             else
-                echo -e "No custom kernel patches available."
+                echo -e "{INFO} Not using apply kernel patches."
             fi
 
-            make_command=""
-            [[ -n "${{ inputs.kernel_source }}" ]] && make_command="${make_command} -r ${{ inputs.kernel_source }}"
-            [[ -n "${{ inputs.kernel_version }}" ]] && make_command="${make_command} -k ${{ inputs.kernel_version }}"
-            [[ -n "${{ inputs.kernel_auto }}" ]] && make_command="${make_command} -a ${{ inputs.kernel_auto }}"
-            [[ -n "${{ inputs.kernel_package }}" ]] && make_command="${make_command} -m ${{ inputs.kernel_package }}"
-            [[ -n "${{ inputs.auto_patch }}" ]] && make_command="${make_command} -p ${{ inputs.auto_patch }}"
-            [[ -n "${{ inputs.kernel_sign }}" ]] && make_command="${make_command} -n ${{ inputs.kernel_sign }}"
-            [[ -n "${{ inputs.kernel_toolchain }}" ]] && make_command="${make_command} -t ${{ inputs.kernel_toolchain }}"
-            [[ -n "${{ inputs.compress_format }}" ]] && make_command="${make_command} -c ${{ inputs.compress_format }}"
-            [[ -n "${{ inputs.delete_source }}" ]] && make_command="${make_command} -d ${{ inputs.delete_source }}"
-            [[ -n "${{ inputs.silent_log }}" ]] && make_command="${make_command} -s ${{ inputs.silent_log }}"
-            sudo ./recompile ${make_command}
+            echo -e "${STEPS} Compiling kernel..."
+            recompile_command=""
+            [[ -n "${{ inputs.kernel_source }}" ]] && recompile_command="${recompile_command} -r ${{ inputs.kernel_source }}"
+            [[ -n "${{ inputs.kernel_version }}" ]] && recompile_command="${recompile_command} -k ${{ inputs.kernel_version }}"
+            [[ -n "${{ inputs.kernel_auto }}" ]] && recompile_command="${recompile_command} -a ${{ inputs.kernel_auto }}"
+            [[ -n "${{ inputs.kernel_package }}" ]] && recompile_command="${recompile_command} -m ${{ inputs.kernel_package }}"
+            [[ -n "${{ inputs.auto_patch }}" ]] && recompile_command="${recompile_command} -p ${{ inputs.auto_patch }}"
+            [[ -n "${{ inputs.kernel_sign }}" ]] && recompile_command="${recompile_command} -n ${{ inputs.kernel_sign }}"
+            [[ -n "${{ inputs.kernel_toolchain }}" ]] && recompile_command="${recompile_command} -t ${{ inputs.kernel_toolchain }}"
+            [[ -n "${{ inputs.compress_format }}" ]] && recompile_command="${recompile_command} -c ${{ inputs.compress_format }}"
+            [[ -n "${{ inputs.delete_source }}" ]] && recompile_command="${recompile_command} -d ${{ inputs.delete_source }}"
+            [[ -n "${{ inputs.silent_log }}" ]] && recompile_command="${recompile_command} -s ${{ inputs.silent_log }}"
+            echo -e "${INFO} Full recompile command: ./recompile ${recompile_command}"
+            sudo ./recompile ${recompile_command}
+            echo -e "${SUCCESS} Kernel compiled."
+
 
             cd ${{ github.action_path }}
             tags="$(ls -l ${PWD}/${kernel_outpath}/*.tar.gz | awk '{print $9}' | grep -oE '[1-9][0-9]{0,2}\.[0-9]{1,3}\.[0-9]+' | xargs | tr "[ ]" "_")"
-            echo -e "Output variables."
             echo "tags=${tags}" >> ${GITHUB_OUTPUT}
             echo "output_path=${PWD}/${kernel_outpath}" >> ${GITHUB_OUTPUT}
             echo "build_date=$(date +"%m.%d.%H%M")" >> ${GITHUB_OUTPUT}
             echo "status=success" >> ${GITHUB_OUTPUT}
-            echo -e "tags: ${tags}"
-            echo -e "output_path: ${PWD}/${kernel_outpath}"
-            echo -e "build_date: $(date +"%m.%d.%H%M")"
-            echo -e "status: success"
-            echo -e "output_path files list: \n$(ls -lh ${PWD}/${kernel_outpath}/ 2>/dev/null)"
+
+            echo -e "${INFO} Final workflow output variables:"
+            echo -e "    tags: ${tags}"
+            echo -e "    output_path: ${PWD}/${kernel_outpath}"
+            echo -e "    build_date: $(date +"%m.%d.%H%M")"
+            echo -e "    status: success"
+            echo -e "    output_path files list: \n$(ls -lh ${PWD}/${kernel_outpath}/ 2>/dev/null)"
 
         else
-            echo -e "Please select a build target: armbian / kernel"
+            echo -e "${ERROR} No build target was selected! It must be either \"armbian\" or \"kernel\""
             exit 1
         fi
 
